// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};

glib::wrapper! {
    ///
    #[doc(alias = "GeglTileSource")]
    pub struct TileSource(Object<ffi::GeglTileSource, ffi::GeglTileSourceClass>);

    match fn {
        type_ => || ffi::gegl_tile_source_get_type(),
    }
}

impl TileSource {
        pub const NONE: Option<&'static TileSource> = None;
    
}
